// Canonical mock output for the private-upload path. Deliberately NOT one of the CC BY corpus
// fixtures — those are real creators' content, and using one as a stand-in for the user's own
// private recording would misattribute it.
//
// Built as an OutputDocument and rendered through the contract renderer, so this mock is
// conformant by construction. With the reference args (demo-billing.mp4 / 2832 s /
// 2026-07-14T10:22:00Z) the result is byte-identical to tests/fixtures/output/private_sample.md —
// enforced by contracts.test.ts, which is what freezes the runtime mock to the contract.

import { renderDocument, type OutputDocument } from './outputDocument';

export interface SampleOutputArgs {
  sourceFilename: string;
  durationSec: number;
  processedAt: string;
}

function formatDuration(totalSeconds: number): string {
  const total = Math.max(0, Math.round(totalSeconds));
  const h = Math.floor(total / 3600);
  const m = Math.floor((total % 3600) / 60);
  const s = total % 60;
  return [h, m, s].map((n) => String(n).padStart(2, '0')).join(':');
}

export function buildSampleDocument({ sourceFilename, durationSec, processedAt }: SampleOutputArgs): OutputDocument {
  return {
    frontmatter: {
      title: 'Q3 Platform Demo — Billing Module',
      source: sourceFilename,
      duration: formatDuration(durationSec),
      language: 'en',
      processed_at: processedAt,
      generator: 'mdreel@0.0.0-fixture',
      summary: "A walkthrough of the billing module's invoice workflow, covering proration and the admin panel.",
      tags: ['demo', 'billing', 'azure'],
    },
    sections: [
      {
        timestamp: '00:00:00',
        heading: 'Introduction',
        blocks: [
          {
            label: 'spoken',
            text: "Thanks for joining — today we'll walk through the billing module, focusing on the new invoice workflow and how proration is applied.",
          },
          { label: 'on_screen', text: 'mdreel — Q3 Platform Demo' },
          { label: 'visual', text: "Title card, then a cut to the presenter's screen share of the admin dashboard." },
        ],
      },
      {
        timestamp: '00:03:40',
        heading: 'Invoice workflow walkthrough',
        blocks: [
          {
            label: 'spoken',
            text: 'We open the invoice editor and apply proration before sending. The service call underneath is a straightforward async create.',
          },
          {
            label: 'on_screen',
            text: 'Invoices → Create → "Apply proration" checkbox\ncode: InvoiceService.CreateAsync(...)',
          },
          {
            label: 'visual',
            text: 'Presenter navigates the admin panel, opens the invoice editor, and toggles the proration checkbox before saving.',
          },
        ],
      },
      {
        timestamp: '00:09:12',
        heading: 'Wrap-up',
        blocks: [
          {
            label: 'spoken',
            text: "That's the core flow — happy to take questions on edge cases like mid-cycle plan changes.",
          },
          { label: 'on_screen', text: 'Questions? billing-team@example.com' },
          { label: 'visual', text: 'Presenter returns to the title card.' },
        ],
      },
    ],
    provenance:
      'Generated by **mdreel** from your uploaded recording. The source video was deleted after processing per the default retention policy.',
  };
}

export function buildSampleOutput(args: SampleOutputArgs): string {
  return renderDocument(buildSampleDocument(args));
}
