using System.Net;
using MdReel.Core.Domain;
using MdReel.Core.Pipeline.StageA;
using MdReel.Core.Pipeline.StageB;
using MdReel.Core.Providers;
using MdReel.Infrastructure.Vertex;
using Microsoft.Extensions.Logging.Abstractions;
using Microsoft.Extensions.Options;

namespace MdReel.Tests.Integration.Vertex;

/// <summary>
/// Item 1 — Vertex 429 region fallback (INFRA.md). Stage B→C back-to-back trips
/// <c>429 RESOURCE_EXHAUSTED</c> on the primary EU region (<c>europe-central2</c>); the analyzer and
/// fuser must retry then fall back to <c>europe-west3</c>, the only other EU region that serves
/// <c>gemini-2.5-flash</c> (CLAUDE.md rule 2). The region actually used is metered (rule 6).
/// Fully offline: a fake handler returns 429 for the primary region and 200 for the fallback.
/// </summary>
public sealed class VertexRegionFallbackTests
{
    private static VertexOptions BuildOptions() => new() { RetryDelay = TimeSpan.Zero };

    [Fact]
    public async Task StageB_falls_back_to_europe_west3_and_meters_that_region()
    {
        var handler = new RegionFallbackHandler(StageBSuccessBody);
        using var httpClient = new HttpClient(handler);
        var analyzer = new VertexVideoAnalyzer(
            httpClient,
            new StubTokenProvider(),
            Options.Create(BuildOptions()),
            NullLogger<VertexVideoAnalyzer>.Instance);

        var ledger = new InMemoryCostLedger();
        var stageB = new StageBRunner(analyzer, ledger);

        var segment = new Segment(
            Index: 0,
            Start: TimeSpan.Zero,
            End: TimeSpan.FromSeconds(180),
            OverlapBefore: TimeSpan.Zero,
            Sampling: new SamplingPlan(MediaResolution.Low, 0),
            Cues: []);

        var analyses = await stageB.AnalyzeAsync(
            "gs://raw-videos-eu/test/source.mp4",
            segment,
            StageAOptions.Default,
            StageBOptions.Default with { ForceCueBoundarySegmentation = false },
            CancellationToken.None,
            jobId: "job-b");

        Assert.NotEmpty(analyses);

        // The primary region was tried and 429'd; the successful call was europe-west3 on the model.
        Assert.Contains(handler.RequestUris, u => u.Contains("europe-central2", StringComparison.Ordinal));
        var success = handler.SucceededUri;
        Assert.NotNull(success);
        Assert.Contains("europe-west3", success, StringComparison.Ordinal);
        Assert.Contains("gemini-2.5-flash", success, StringComparison.Ordinal);

        var entry = Assert.Single(ledger.Entries, e => e.Step == "stage_b.analyze");
        Assert.Equal("europe-west3", entry.Region);
        Assert.Equal("job-b", entry.JobId);
        Assert.Equal(CostKind.Llm, entry.Kind);
    }

    [Fact]
    public async Task StageC_falls_back_to_europe_west3_and_meters_that_region()
    {
        var handler = new RegionFallbackHandler(FusionSuccessBody);
        using var httpClient = new HttpClient(handler);
        var ledger = new InMemoryCostLedger();
        var fuser = new VertexTextFuser(
            httpClient,
            new StubTokenProvider(),
            Options.Create(BuildOptions()),
            ledger,
            NullLogger<VertexTextFuser>.Instance);

        var analyses = new[]
        {
            new SegmentAnalysis(
                SegmentIndex: 0,
                SegmentStart: TimeSpan.Zero,
                Language: "en",
                Blocks:
                [
                    new AnalyzedBlock(TimeSpan.FromSeconds(5), "hello", "Speaker 1", "", "a slide", "slide"),
                ],
                Summary: "sum"),
        };

        var request = new FusionRequest(
            Source: "clip.mp4",
            Duration: TimeSpan.FromSeconds(180),
            Provenance: "Generated by mdreel.",
            Generator: "mdreel@test",
            JobId: "job-c");

        var document = await fuser.FuseAsync(analyses, request, CancellationToken.None);

        Assert.NotEmpty(document.Sections);
        Assert.Contains(handler.RequestUris, u => u.Contains("europe-central2", StringComparison.Ordinal));
        var success = handler.SucceededUri;
        Assert.NotNull(success);
        Assert.Contains("europe-west3", success, StringComparison.Ordinal);
        Assert.Contains("gemini-2.5-flash", success, StringComparison.Ordinal);

        var entry = Assert.Single(ledger.Entries, e => e.Step == "stage_c.fuse");
        Assert.Equal("europe-west3", entry.Region);
        Assert.Equal("job-c", entry.JobId);
    }

    // 429 on europe-central2 (with no Retry-After so the test does not wait), 200 on europe-west3.
    private sealed class RegionFallbackHandler(string successBody) : HttpMessageHandler
    {
        public List<string> RequestUris { get; } = [];

        public string? SucceededUri { get; private set; }

        protected override Task<HttpResponseMessage> SendAsync(
            HttpRequestMessage request,
            CancellationToken cancellationToken)
        {
            var uri = request.RequestUri!.ToString();
            RequestUris.Add(uri);

            if (uri.Contains("europe-central2", StringComparison.Ordinal))
            {
                return Task.FromResult(new HttpResponseMessage(HttpStatusCode.TooManyRequests)
                {
                    Content = new StringContent("{\"error\":\"RESOURCE_EXHAUSTED\"}"),
                });
            }

            SucceededUri = uri;
            return Task.FromResult(new HttpResponseMessage(HttpStatusCode.OK)
            {
                Content = new StringContent(successBody),
            });
        }
    }

    private sealed class StubTokenProvider : IAccessTokenProvider
    {
        public Task<string> GetTokenAsync(CancellationToken cancellationToken) =>
            Task.FromResult("test-token");
    }

    private const string StageBSuccessBody = """
        {
          "candidates": [
            {
              "finishReason": "STOP",
              "content": {
                "role": "model",
                "parts": [
                  {
                    "text": "{\"segment_start\":\"00:00:00\",\"language\":\"en\",\"segment_summary\":\"sum\",\"blocks\":[{\"t\":\"00:00:10\",\"spoken\":\"a\",\"speaker\":\"Speaker 1\",\"on_screen_text\":\"\",\"visual\":\"v1\",\"kind\":\"demo\"},{\"t\":\"00:01:10\",\"spoken\":\"b\",\"speaker\":\"Speaker 1\",\"on_screen_text\":\"\",\"visual\":\"v2\",\"kind\":\"demo\"},{\"t\":\"00:03:00\",\"spoken\":\"c\",\"speaker\":\"Speaker 1\",\"on_screen_text\":\"\",\"visual\":\"v3\",\"kind\":\"demo\"}]}"
                  }
                ]
              }
            }
          ]
        }
        """;

    private const string FusionSuccessBody = """
        {
          "candidates": [
            {
              "finishReason": "STOP",
              "content": {
                "role": "model",
                "parts": [
                  {
                    "text": "{\"title\":\"Test\",\"summary\":\"A short test summary.\",\"language\":\"en\",\"tags\":[\"test\"],\"sections\":[{\"timestamp\":\"00:00:00\",\"heading\":\"Intro\",\"blocks\":[{\"label\":\"spoken\",\"text\":\"hello\"}]}]}"
                  }
                ]
              }
            }
          ]
        }
        """;
}
