using System.Net;
using MdReel.Core.Domain;
using MdReel.Core.Output;
using MdReel.Core.Providers;
using MdReel.Infrastructure.Vertex;
using Microsoft.Extensions.Logging.Abstractions;
using Microsoft.Extensions.Options;

namespace MdReel.Tests.Integration.Vertex;

/// <summary>
/// §4 requires section timestamps to be strictly ascending, and the first real corpus run showed
/// the fusion model does not guarantee that on its own — production failed with
/// "section timestamps are not strictly ascending". Two independent causes:
/// the model emits sections out of order, and adjacent segments <b>overlap by design</b>, so two
/// of them legitimately describe the same moment and fuse to the same timestamp.
///
/// These tests pin the deterministic repair. Fully offline.
/// </summary>
public sealed class VertexFusionOrderingTests
{
    [Fact]
    public async Task Out_of_order_sections_are_sorted_into_the_contract_order()
    {
        var document = await FuseAsync("""
            {"title":"T","summary":"A short summary.","language":"en","tags":["t"],"sections":[
              {"timestamp":"00:07:30","heading":"Third","blocks":[{"label":"spoken","text":"c"}]},
              {"timestamp":"00:00:10","heading":"First","blocks":[{"label":"spoken","text":"a"}]},
              {"timestamp":"00:04:24","heading":"Second","blocks":[{"label":"spoken","text":"b"}]}
            ]}
            """);

        Assert.Equal(["00:00:10", "00:04:24", "00:07:30"], document.Sections.Select(s => s.Timestamp));
        Assert.Equal(["First", "Second", "Third"], document.Sections.Select(s => s.Heading));
    }

    [Fact]
    public async Task Colliding_timestamps_are_merged_rather_than_dropped()
    {
        // The 20-second segment overlap exists precisely so nothing is lost at a boundary.
        // Dropping the second section would throw away what the overlap was bought to keep.
        var document = await FuseAsync("""
            {"title":"T","summary":"A short summary.","language":"en","tags":["t"],"sections":[
              {"timestamp":"00:04:24","heading":"Boundary","blocks":[{"label":"spoken","text":"from segment one"}]},
              {"timestamp":"00:04:24","heading":"Boundary again","blocks":[{"label":"on_screen","text":"from segment two"}]},
              {"timestamp":"00:09:00","heading":"Later","blocks":[{"label":"spoken","text":"later"}]}
            ]}
            """);

        Assert.Equal(["00:04:24", "00:09:00"], document.Sections.Select(s => s.Timestamp));

        var boundary = document.Sections[0];
        Assert.Equal("Boundary", boundary.Heading);
        Assert.Contains(boundary.Blocks, b => b.Label == OutputBlockLabel.Spoken && b.Text == "from segment one");
        Assert.Contains(boundary.Blocks, b => b.Label == OutputBlockLabel.OnScreen && b.Text == "from segment two");
    }

    [Fact]
    public async Task The_rendered_document_satisfies_the_output_contract()
    {
        // The end-to-end assertion: whatever order the model returns, what leaves Stage C renders.
        var document = await FuseAsync("""
            {"title":"T","summary":"A short summary.","language":"en","tags":["t"],"sections":[
              {"timestamp":"00:04:24","heading":"B","blocks":[{"label":"spoken","text":"b"}]},
              {"timestamp":"00:04:24","heading":"B dup","blocks":[{"label":"visual","text":"v"}]},
              {"timestamp":"00:00:00","heading":"A","blocks":[{"label":"spoken","text":"a"}]}
            ]}
            """);

        var markdown = OutputMarkdownRenderer.Render(document);

        Assert.Contains("[00:00:00]", markdown, StringComparison.Ordinal);
        Assert.True(
            markdown.IndexOf("[00:00:00]", StringComparison.Ordinal)
            < markdown.IndexOf("[00:04:24]", StringComparison.Ordinal));
    }

    private static async Task<OutputDocument> FuseAsync(string payloadJson)
    {
        var body = "{\"candidates\":[{\"finishReason\":\"STOP\",\"content\":{\"role\":\"model\",\"parts\":[{\"text\":"
            + System.Text.Json.JsonSerializer.Serialize(payloadJson)
            + "}]}}]}";

        using var httpClient = new HttpClient(new AlwaysOkHandler(body));
        var fuser = new VertexTextFuser(
            httpClient,
            new StubToken(),
            Options.Create(new VertexOptions { RetryDelay = TimeSpan.Zero }),
            new InMemoryCostLedger(),
            NullLogger<VertexTextFuser>.Instance);

        return await fuser.FuseAsync(
            [
                new SegmentAnalysis(0, TimeSpan.Zero, "en",
                    [new AnalyzedBlock(TimeSpan.FromSeconds(5), "hello", "Speaker 1", "", "a slide", "slide")],
                    "sum"),
            ],
            new FusionRequest("clip.mp4", TimeSpan.FromMinutes(20), "Generated by mdreel.", "mdreel@test", "job-order"),
            CancellationToken.None);
    }

    private sealed class AlwaysOkHandler(string body) : HttpMessageHandler
    {
        protected override Task<HttpResponseMessage> SendAsync(
            HttpRequestMessage request,
            CancellationToken cancellationToken) =>
            Task.FromResult(new HttpResponseMessage(HttpStatusCode.OK)
            {
                Content = new StringContent(body),
            });
    }

    private sealed class StubToken : IAccessTokenProvider
    {
        public Task<string> GetTokenAsync(CancellationToken cancellationToken) => Task.FromResult("test-token");
    }
}
