#!/usr/bin/env npx tsx
// Normalizes the frozen Phase-0.2 experiment outputs into the ratified output contract
// (ARCHITECTURE §4) and writes the canonical fixtures to tests/fixtures/output/.
//
// Run from web/:  npx tsx scripts/normalize-fixtures.mts
//
// experiments/** is a point-in-time record and is NEVER rewritten (PLAN.md) — this script reads
// it and writes normalized copies. It carries its own *tolerant* reader (adapted from the
// pre-Phase-2.5 lib/corpus.ts parser) on purpose: lib/outputDocument.ts is strict and would
// reject the un-normalized originals, so the tolerant grammar lives only here, quarantined with
// the one-off conversion. Committed for reproducibility, not for routine use — the canonical
// fixtures under tests/fixtures/output/ are the contract artifacts.
//
// What it normalizes (the Phase 2.5 contract rulings):
//   - CRLF → LF; bracketless "## hh:mm:ss" headings → "## [hh:mm:ss]"
//   - block order → spoken, on_screen, visual; labels inline (On screen: label + "> " lines)
//   - blank internal lines dropped; stray "> " prefixes stripped from spoken/visual text
//   - H1 := frontmatter.title; source_filename → source; generator → mdreel@0.0.0-fixture
//   - "Generated by **vectorreel**" → "**mdreel**" in the provenance prose (attribution
//     blockquotes untouched — they must stay identical to corpus.json's attribution field)
// It also emits the .json twin of every .md (the output.json contract shape) and the frozen
// private-path sample, and asserts parse→render byte round-trips before writing anything.

import { mkdirSync, readFileSync, readdirSync, writeFileSync, copyFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';
import assert from 'node:assert/strict';
import matter from 'gray-matter';
import {
  parseDocument,
  renderDocument,
  type BlockLabel,
  type OutputBlock,
  type OutputDocument,
  type OutputSection,
} from '../lib/outputDocument';
import { buildSampleDocument } from '../lib/sampleOutput';

const __dirname = dirname(fileURLToPath(import.meta.url));
const webRoot = join(__dirname, '..');
const repoRoot = join(webRoot, '..');
const sourceDir = join(repoRoot, 'experiments', '001-gemini-video-benchmark', 'out');
const destDir = join(repoRoot, 'tests', 'fixtures', 'output');

const FIXTURE_GENERATOR = 'mdreel@0.0.0-fixture';
const PROVENANCE_HEADING = '## Source & licence';

// --- tolerant reader (the pre-contract grammar, verbatim behaviour) ---

const TOLERANT_HEADING_RE = /^##\s+\[?(\d{2}:\d{2}:\d{2})\]?\s+(.+)$/;
const TOLERANT_LABELS: { label: BlockLabel; re: RegExp }[] = [
  { label: 'spoken', re: /^\*\*Spoken:\*\*\s?(.*)$/ },
  { label: 'on_screen', re: /^\*\*On screen:\*\*\s?(.*)$/ },
  { label: 'visual', re: /^\*\*Visual:\*\*\s?(.*)$/ },
];
const LABEL_ORDER: BlockLabel[] = ['spoken', 'on_screen', 'visual'];

interface TolerantChunk {
  heading: string;
  body: string;
}

function splitIntoHeadingChunks(content: string): TolerantChunk[] {
  const chunks: TolerantChunk[] = [];
  let heading: string | null = null;
  let body: string[] = [];
  for (const line of content.split('\n')) {
    if (line.startsWith('## ')) {
      if (heading !== null) chunks.push({ heading, body: body.join('\n') });
      heading = line;
      body = [];
    } else if (heading !== null) {
      body.push(line);
    }
  }
  if (heading !== null) chunks.push({ heading, body: body.join('\n') });
  return chunks;
}

function cleanBlockText(text: string): string {
  return text
    .split('\n')
    .map((line) => line.replace(/^>\s?/, '').trimEnd())
    .filter((line) => line.trim().length > 0)
    .join('\n');
}

function parseTolerantBlocks(file: string, timestamp: string, body: string): OutputBlock[] {
  const collected = new Map<BlockLabel, string[]>();
  let current: { label: BlockLabel; text: string } | null = null;
  const flush = () => {
    if (!current) return;
    const text = cleanBlockText(current.text);
    if (text.length > 0) {
      const bucket = collected.get(current.label) ?? [];
      bucket.push(text);
      collected.set(current.label, bucket);
    }
    current = null;
  };
  for (const line of body.split('\n')) {
    if (line.trim() === '---') break; // the document rule before "## Source & licence", not content
    const hit = TOLERANT_LABELS.find(({ re }) => re.test(line));
    if (hit) {
      flush();
      current = { label: hit.label, text: hit.re.exec(line)![1] ?? '' };
    } else if (current) {
      current.text += `\n${line}`;
    }
  }
  flush();

  const blocks: OutputBlock[] = [];
  for (const label of LABEL_ORDER) {
    const bucket = collected.get(label);
    if (!bucket) continue;
    if (bucket.length > 1) {
      console.warn(`  ⚠ ${file} [${timestamp}]: merging ${bucket.length} "${label}" blocks`);
    }
    blocks.push({ label, text: bucket.join('\n') });
  }
  return blocks;
}

function normalizeCorpusFile(file: string): OutputDocument {
  const raw = readFileSync(join(sourceDir, 'corpus_md', file), 'utf-8').replace(/\r\n/g, '\n');
  const { data, content } = matter(raw);

  const sections: OutputSection[] = [];
  let provenance: string | null = null;
  for (const { heading, body } of splitIntoHeadingChunks(content)) {
    const m = TOLERANT_HEADING_RE.exec(heading);
    if (m) {
      const timestamp = m[1];
      sections.push({
        timestamp,
        heading: m[2].trim(),
        blocks: parseTolerantBlocks(file, timestamp, body),
      });
      continue;
    }
    if (heading.trim() === PROVENANCE_HEADING) {
      provenance = body
        .replace(/\n---\s*$/, '') // no trailing rule inside the section body
        .trim()
        .replace('Generated by **vectorreel**', 'Generated by **mdreel**');
      continue;
    }
    throw new Error(`${file}: unexpected H2 ${JSON.stringify(heading)}`);
  }
  if (!provenance) throw new Error(`${file}: no "${PROVENANCE_HEADING}" section`);

  return {
    frontmatter: {
      title: String(data.title),
      source: String(data.source_filename),
      duration: String(data.duration),
      language: String(data.language),
      processed_at: String(data.processed_at),
      generator: FIXTURE_GENERATOR,
      summary: String(data.summary),
      tags: (data.tags as string[]).map(String),
    },
    sections,
    provenance,
  };
}

// --- the frozen private-path sample (the §4 example, in contract form) ---
// lib/sampleOutput.ts builds the same document at runtime with the user's own filename/duration;
// contracts.test.ts asserts its output with these exact reference args is byte-identical to the
// committed fixture.

export const PRIVATE_SAMPLE_ARGS = {
  sourceFilename: 'demo-billing.mp4',
  durationSec: 2832,
  processedAt: '2026-07-14T10:22:00Z',
} as const;

function buildPrivateSample(): OutputDocument {
  return buildSampleDocument(PRIVATE_SAMPLE_ARGS);
}

// --- main ---

mkdirSync(destDir, { recursive: true });

const documents = new Map<string, OutputDocument>();
for (const file of readdirSync(join(sourceDir, 'corpus_md'))) {
  if (!file.endsWith('.md')) continue;
  documents.set(file, normalizeCorpusFile(file));
}
documents.set('private_sample.md', buildPrivateSample());

for (const [file, doc] of documents) {
  const rendered = renderDocument(doc);
  const reparsed = parseDocument(rendered);
  assert.deepEqual(reparsed, doc, `${file}: parse(render(doc)) round-trip`);
  assert.equal(renderDocument(reparsed), rendered, `${file}: render(parse(md)) byte round-trip`);

  writeFileSync(join(destDir, file), rendered);
  writeFileSync(join(destDir, file.replace(/\.md$/, '.json')), `${JSON.stringify(doc, null, 2)}\n`);
  console.log(`wrote ${file} (+ .json), ${doc.sections.length} sections`);
}

copyFileSync(join(sourceDir, 'corpus.json'), join(destDir, 'corpus.json'));
console.log('copied corpus.json');
console.log(`\nNormalized ${documents.size} documents into ${destDir}`);
