using MdReel.Core.Domain;
using MdReel.Core.Output;
using MdReel.Core.Pipeline.StageA;
using MdReel.Core.Pipeline.StageB;
using MdReel.Core.Providers;
using MdReel.Infrastructure.Pipeline;

namespace MdReel.Tests.Integration;

/// <summary>
/// The record/replay harness against the committed <c>tests/fixtures/llm</c> fixtures. This is how the
/// default suite gets Stage B/C fidelity with zero Vertex spend and no network: a real recorded (here,
/// deterministically generated) model response flows through the real Stage B guards, the fuser, and
/// the frozen Markdown renderer. Refresh the fixtures with <c>PipelineModel:Mode=Record</c> (TESTING.md).
/// </summary>
public sealed class PipelineReplayHarnessTests
{
    private static string FixturesDirectory => Path.Combine(Fixtures.RepoRoot, "tests", "fixtures", "llm");

    // The canonical fixture window: the committed nasa clip is one 90-second segment at default
    // resolution. The fixture key depends only on this window, so it is stable across machines.
    private static Segment CanonicalSegment => new(
        Index: 0,
        Start: TimeSpan.Zero,
        End: TimeSpan.FromSeconds(90),
        OverlapBefore: TimeSpan.Zero,
        Sampling: new SamplingPlan(MediaResolution.Default, 0),
        Cues: []);

    private static StageBOptions Options => StageBOptions.Default with { ForceCueBoundarySegmentation = false };

    [Fact]
    public async Task Replays_committed_fixtures_through_real_guards_and_renderer()
    {
        var store = new FixtureStore(FixturesDirectory);
        var stageB = new StageBRunner(new ReplayVideoAnalyzer(store));

        var analyses = await stageB.AnalyzeAsync(
            "fixture://nasa", CanonicalSegment, StageAOptions.Default, Options, CancellationToken.None);

        var analysis = Assert.Single(analyses);
        Assert.Equal("en", analysis.Language);
        Assert.NotEmpty(analysis.Blocks);
        // Stage B's normalizer + coverage guard accepted the fixture; offsets must be ascending.
        var offsets = analysis.Blocks.Select(b => b.At).ToArray();
        Assert.Equal(offsets.OrderBy(x => x).ToArray(), offsets);

        var fuser = new ReplayTextFuser(store);
        var request = new FusionRequest(
            Source: "talking_head_nasa_bolten.mp4",
            Duration: TimeSpan.FromSeconds(90),
            Provenance: "Generated by **mdreel** from your uploaded recording.",
            Generator: "mdreel@9.9.9-test");
        var document = await fuser.FuseAsync(analyses, request, CancellationToken.None);

        // The pipeline owns identity/provenance — the replayed body is stamped with this job's facts.
        Assert.Equal("talking_head_nasa_bolten.mp4", document.Frontmatter.Source);
        Assert.Equal("mdreel@9.9.9-test", document.Frontmatter.Generator);

        var markdown = OutputMarkdownRenderer.Render(document);
        Assert.StartsWith("---\n", markdown, StringComparison.Ordinal);
        Assert.Contains("source: \"talking_head_nasa_bolten.mp4\"", markdown, StringComparison.Ordinal);
        Assert.Contains("## Source & licence", markdown, StringComparison.Ordinal);
    }

    [Fact]
    public async Task Missing_fixture_fails_loudly()
    {
        var store = new FixtureStore(FixturesDirectory);
        var stageB = new StageBRunner(new ReplayVideoAnalyzer(store));

        // A window with no committed fixture must throw, not silently invent output.
        var unknown = CanonicalSegment with { Start = TimeSpan.FromSeconds(500), End = TimeSpan.FromSeconds(590) };

        await Assert.ThrowsAsync<FileNotFoundException>(() =>
            stageB.AnalyzeAsync("fixture://nasa", unknown, StageAOptions.Default, Options, CancellationToken.None));
    }
}
