using System.Diagnostics;
using System.Text;
using System.Text.Json;
using MdReel.Core.Domain;
using MdReel.Core.Output;
using MdReel.Core.Pipeline.StageA;
using MdReel.Core.Providers;
using Microsoft.Extensions.Logging;

namespace MdReel.Core.Pipeline.StageB;

/// <summary>
/// Internal-only runner for gallery production from YouTube <c>fileData.fileUri</c> sources.
/// No public endpoint should call this path.
/// </summary>
public sealed class YouTubeInternalGalleryRunner(
    StageBRunner stageB,
    ITextFuser fuser,
    IObjectStorage objectStorage,
    ICostLedger ledger,
    ILogger<YouTubeInternalGalleryRunner> logger)
{
    private const string GeneratorId = "mdreel@0.0.0-internal";

    // Gallery outputs are curated + CC-licensed + attributed (CLAUDE.md rule 8). Per-video
    // attribution is supplied on the request and rendered into the "## Source & licence" section;
    // this is the fallback body when a request carries none.
    private const string GalleryProvenance =
        "Generated by **mdreel** from a publicly available, CC-licensed recording. See the source "
        + "link for attribution and the exact licence.";

    private static readonly JsonSerializerOptions DocumentJson = new() { WriteIndented = true };

    public async Task<YouTubeInternalGalleryRunResult> RunAsync(
        YouTubeInternalGalleryRunRequest request,
        StageBOptions stageBOptions,
        CancellationToken cancellationToken)
    {
        ArgumentNullException.ThrowIfNull(request);
        ArgumentNullException.ThrowIfNull(stageBOptions);

        var stopwatch = Stopwatch.StartNew();
        var outcome = "failed";
        using var jobActivity = PipelineDiagnostics.Source.StartActivity(
            "pipeline.job", ActivityKind.Internal, parentContext: default);
        jobActivity?.SetTag("mdreel.job_id", request.JobId);
        jobActivity?.SetTag("jobId", request.JobId);

        try
        {
            EnsureYouTubeUri(request.SourceUri);

            var segments = PlanSegments(
                request.Duration,
                request.SegmentLength,
                request.SegmentOverlap,
                request.MediaResolution);

            var prefix = BuildPrefix(request.OutputPrefix, request.VideoId);

            List<SegmentAnalysis> analyses = [];
            using (StartStage(request.JobId, "B"))
            {
                foreach (var segment in segments)
                {
                    // Segment-level checkpointing. Vertex returns 429 in both EU regions under
                    // shared-quota contention, so a long video can fail at segment 5 having already
                    // paid for segments 0-4. Without this, the retry buys them a second time
                    // (CLAUDE.md rule 6 — the cheapest euro is the one not spent twice).
                    var checkpoint = $"{prefix}/segments/{segment.Index:D3}.json";
                    if (request.CheckpointSegments
                        && await TryReadSegmentAsync(request.OutputBucket, checkpoint, cancellationToken)
                            is { } cached)
                    {
                        analyses.AddRange(cached);
                        continue;
                    }

                    var analyzed = await stageB.AnalyzeAsync(
                        request.SourceUri,
                        segment,
                        StageAOptions.Default,
                        stageBOptions,
                        cancellationToken,
                        request.JobId);

                    if (request.CheckpointSegments)
                    {
                        await WriteUtf8Async(
                            request.OutputBucket,
                            checkpoint,
                            JsonSerializer.Serialize(analyzed, DocumentJson),
                            cancellationToken);
                    }

                    analyses.AddRange(analyzed);
                }
            }

            analyses = [.. analyses.OrderBy(static x => x.SegmentStart).ThenBy(static x => x.SegmentIndex)];
            var fusionRequest = new FusionRequest(
                Source: request.SourceUri,
                Duration: request.Duration,
                Provenance: BuildProvenance(request.Attribution),
                Generator: GeneratorId,
                JobId: request.JobId);
            OutputDocument document;
            using (StartStage(request.JobId, "C", recordMetric: true))
            {
                document = await fuser.FuseAsync(analyses, fusionRequest, cancellationToken);
            }

            var markdown = OutputMarkdownRenderer.Render(document);

            var stageBPath = $"{prefix}/stage-b.json";
            var outputMarkdownPath = $"{prefix}/output.md";
            var outputJsonPath = $"{prefix}/output.json";

            using (StartStage(request.JobId, "D", recordMetric: true))
            {
                await WriteUtf8Async(
                    request.OutputBucket,
                    stageBPath,
                    JsonSerializer.Serialize(new
                    {
                        job_id = request.JobId,
                        source_uri = request.SourceUri,
                        generated_at = DateTimeOffset.UtcNow,
                        segments = analyses,
                    }),
                    cancellationToken);

                await WriteUtf8Async(
                    request.OutputBucket,
                    outputMarkdownPath,
                    markdown,
                    cancellationToken);

                await WriteUtf8Async(
                    request.OutputBucket,
                    outputJsonPath,
                    JsonSerializer.Serialize(document, DocumentJson),
                    cancellationToken);
            }

            if (logger.IsEnabled(LogLevel.Information))
            {
                logger.LogInformation(
                    "YouTube internal runner finished job {JobId} ({VideoId}) with {Segments} Stage-B segments; {LlmCalls} LLM calls metered",
                    request.JobId,
                    request.VideoId,
                    analyses.Count,
                    CountMeteredLlmCalls(request.JobId));
            }

            outcome = "completed";
            PipelineDiagnostics.AddJobVideoMinutes(request.Duration);
            return new YouTubeInternalGalleryRunResult(
                request.JobId,
                request.VideoId,
                analyses.Count,
                outputMarkdownPath,
                stageBPath);
        }
        catch (Exception ex)
        {
            jobActivity?.SetStatus(ActivityStatusCode.Error, ex.Message);
            throw;
        }
        finally
        {
            stopwatch.Stop();
            PipelineDiagnostics.RecordJobDuration(stopwatch.Elapsed, outcome);
        }
    }

    private static StageActivityScope StartStage(string jobId, string stage, bool recordMetric = false)
    {
        var activity = PipelineDiagnostics.Source.StartActivity($"pipeline.stage.{stage}");
        activity?.SetTag("mdreel.job_id", jobId);
        activity?.SetTag("jobId", jobId);
        activity?.SetTag("mdreel.stage", stage);
        return new StageActivityScope(activity, stage, recordMetric);
    }

    // The "## Source & licence" body: attribution is mandatory for the gallery (CLAUDE.md rule 8),
    // so a curated request carries it; the constant is only the last-resort fallback.
    private static string BuildProvenance(GalleryAttribution? attribution)
    {
        if (attribution is null)
        {
            return GalleryProvenance;
        }

        var builder = new StringBuilder("Generated by **mdreel** from ");
        builder.Append('"').Append(attribution.Title.Trim()).Append('"');
        if (!string.IsNullOrWhiteSpace(attribution.Author))
        {
            builder.Append(" by ").Append(attribution.Author.Trim());
        }

        builder.Append(", licensed ").Append(attribution.Licence.Trim()).Append('.');
        if (!string.IsNullOrWhiteSpace(attribution.SourceUrl))
        {
            builder.Append(" Source: ").Append(attribution.SourceUrl.Trim()).Append('.');
        }

        return builder.ToString();
    }

    // Evidence for the shakedown that rule 6 held: the real metering happens in StageBRunner + the
    // Vertex fuser; this only reports the count when the in-memory ledger is in use (the worker).
    private int CountMeteredLlmCalls(string jobId) =>
        ledger is InMemoryCostLedger inMemory
            ? inMemory.Entries.Count(e =>
                e.Kind == CostKind.Llm && string.Equals(e.JobId, jobId, StringComparison.Ordinal))
            : 0;

    internal static IReadOnlyList<Segment> PlanSegments(
        TimeSpan duration,
        TimeSpan segmentLength,
        TimeSpan overlap,
        MediaResolution mediaResolution = MediaResolution.Default)
    {
        if (duration <= TimeSpan.Zero)
        {
            throw new ArgumentOutOfRangeException(nameof(duration), "Duration must be positive.");
        }

        if (segmentLength <= TimeSpan.Zero)
        {
            throw new ArgumentOutOfRangeException(nameof(segmentLength), "Segment length must be positive.");
        }

        if (overlap < TimeSpan.Zero || overlap >= segmentLength)
        {
            throw new ArgumentOutOfRangeException(nameof(overlap), "Overlap must be >= 0 and shorter than segment length.");
        }

        List<Segment> segments = [];
        var cursor = TimeSpan.Zero;
        var index = 0;

        while (cursor < duration)
        {
            var end = cursor + segmentLength;
            if (end > duration)
            {
                end = duration;
            }

            var overlapBefore = index == 0 ? TimeSpan.Zero : overlap;
            var start = cursor - overlapBefore;
            if (start < TimeSpan.Zero)
            {
                start = TimeSpan.Zero;
                overlapBefore = TimeSpan.Zero;
            }

            segments.Add(new Segment(
                Index: index,
                Start: start,
                End: end,
                OverlapBefore: overlapBefore,
                Sampling: new SamplingPlan(mediaResolution, 0),
                Cues: []));

            index++;
            cursor += segmentLength;
        }

        return segments;
    }

    internal static void EnsureYouTubeUri(string sourceUri)
    {
        ArgumentException.ThrowIfNullOrWhiteSpace(sourceUri);

        if (!Uri.TryCreate(sourceUri, UriKind.Absolute, out var parsed))
        {
            throw new ArgumentException("SourceUri must be a valid absolute URI.", nameof(sourceUri));
        }

        var isYouTubeHost =
            string.Equals(parsed.Host, "youtu.be", StringComparison.OrdinalIgnoreCase)
            || parsed.Host.EndsWith(".youtube.com", StringComparison.OrdinalIgnoreCase)
            || string.Equals(parsed.Host, "youtube.com", StringComparison.OrdinalIgnoreCase);

        if (!isYouTubeHost || parsed.Scheme != Uri.UriSchemeHttps)
        {
            throw new ArgumentException(
                "Internal YouTube runner accepts only https://youtube.com or https://youtu.be sources.",
                nameof(sourceUri));
        }
    }

    /// <summary>
    /// Reads a checkpointed segment back. A checkpoint that cannot be read is treated as absent and
    /// re-analysed: paying for one segment again is cheap, and trusting a half-written file is not.
    /// </summary>
    private async Task<IReadOnlyList<SegmentAnalysis>?> TryReadSegmentAsync(
        string bucket,
        string objectName,
        CancellationToken cancellationToken)
    {
        if (!await objectStorage.ExistsAsync(bucket, objectName, cancellationToken))
        {
            return null;
        }

        try
        {
            await using var stream = await objectStorage.OpenReadAsync(bucket, objectName, cancellationToken);
            using var reader = new StreamReader(stream, Encoding.UTF8);
            var json = await reader.ReadToEndAsync(cancellationToken);
            var cached = JsonSerializer.Deserialize<List<SegmentAnalysis>>(json);
            return cached is { Count: > 0 } ? cached : null;
        }
        catch (JsonException)
        {
            logger.LogWarning("Segment checkpoint {Object} was unreadable; re-analysing it.", objectName);
            return null;
        }
    }

    private async Task WriteUtf8Async(string bucket, string objectName, string content, CancellationToken cancellationToken)
    {
        await using var stream = new MemoryStream(Encoding.UTF8.GetBytes(content));
        await objectStorage.WriteAsync(bucket, objectName, stream, cancellationToken);
    }

    private static string BuildPrefix(string outputPrefix, string videoId)
    {
        var trimmed = outputPrefix.Trim().Trim('/');
        return string.IsNullOrEmpty(trimmed) ? videoId : $"{trimmed}/{videoId}";
    }
}

/// <remarks>
/// <c>MediaResolution</c> is the request-level cost lever on this path (METRICS.md <b>N4b</b>).
/// Stage A's per-segment static routing is impossible without the bytes, but media resolution needs
/// no local analysis — so internal gallery/collection production runs blanket-low, which is what
/// METRICS.md <b>N4c</b> assumes. Defaults to <see cref="Domain.MediaResolution.Default"/> so
/// nothing changes for callers that have not opted in.
/// </remarks>
public sealed record YouTubeInternalGalleryRunRequest(
    string JobId,
    string VideoId,
    string SourceUri,
    TimeSpan Duration,
    string OutputBucket,
    string OutputPrefix,
    TimeSpan SegmentLength,
    TimeSpan SegmentOverlap,
    GalleryAttribution? Attribution = null,
    MediaResolution MediaResolution = MediaResolution.Default,
    bool CheckpointSegments = false);

/// <summary>
/// Curated attribution for a gallery source (CLAUDE.md rule 8 — every gallery output is
/// CC-licensed and attributed). Rendered into the output's "## Source &amp; licence" section.
/// </summary>
public sealed record GalleryAttribution(
    string Title,
    string Author,
    string Licence,
    string SourceUrl);

public sealed record YouTubeInternalGalleryRunResult(
    string JobId,
    string VideoId,
    int StageBSegments,
    string OutputMarkdownObject,
    string StageBRawObject);

internal sealed class StageActivityScope(Activity? activity, string stage, bool recordMetric) : IDisposable
{
    private readonly Stopwatch _stopwatch = Stopwatch.StartNew();

    public void Dispose()
    {
        _stopwatch.Stop();
        if (recordMetric)
        {
            PipelineDiagnostics.RecordStageDuration(stage, _stopwatch.Elapsed);
        }

        activity?.Dispose();
    }
}
