using MdReel.Core.Domain;
using MdReel.Core.Pipeline.StageA;
using MdReel.Core.Pipeline.StageB;
using MdReel.Core.Providers;
using MdReel.Infrastructure.Vertex;
using Microsoft.Extensions.Logging.Abstractions;

namespace MdReel.Tests.Live;

/// <summary>
/// Real Vertex Stage B + Stage C smoke against a CC-licensed YouTube source (fileData.fileUri —
/// Google fetches it, we never download bytes, CLAUDE.md rule 8). Costs real money; Category=Live
/// keeps it out of the default suite. Run before deploys / when prompts or schemas change (rule 5).
///
/// Source and window are overridable via env (MDREEL_LIVE_SOURCE_URI / MDREEL_LIVE_DURATION_SEC);
/// the default is Blender's Big Buck Bunny (CC-BY), analysed at low resolution over a short window
/// to keep the smoke cheap.
/// </summary>
[Trait("Category", "Live")]
public sealed class VertexStageBLiveTests
{
    private static string SourceUri =>
        Environment.GetEnvironmentVariable("MDREEL_LIVE_SOURCE_URI")
        ?? "https://www.youtube.com/watch?v=aqz-KE-bpKQ";

    private static int WindowSeconds =>
        int.TryParse(Environment.GetEnvironmentVariable("MDREEL_LIVE_DURATION_SEC"), out var s) ? s : 20;

    private static VertexOptions Options => new();

    [Fact]
    public async Task StageB_then_StageC_produce_a_valid_document()
    {
        using var httpClient = new HttpClient();
        var tokenProvider = new AdcAccessTokenProvider();
        var options = Microsoft.Extensions.Options.Options.Create(Options);

        var analyzer = new VertexVideoAnalyzer(
            httpClient, tokenProvider, options, NullLogger<VertexVideoAnalyzer>.Instance);
        var stageB = new StageBRunner(analyzer);

        var segment = new Segment(
            Index: 0,
            Start: TimeSpan.Zero,
            End: TimeSpan.FromSeconds(WindowSeconds),
            OverlapBefore: TimeSpan.Zero,
            // Low resolution: ~66 video tokens/sec vs 258 — a quarter of the cost for a smoke.
            Sampling: new SamplingPlan(MediaResolution.Low, 0),
            Cues: []);

        var stageBOptions = StageBOptions.Default with { ForceCueBoundarySegmentation = false };
        var analyses = await stageB.AnalyzeAsync(
            SourceUri, segment, StageAOptions.Default, stageBOptions, CancellationToken.None);

        Assert.NotEmpty(analyses);
        Assert.All(analyses, a => Assert.NotEmpty(a.Blocks));

        using var fuserHttp = new HttpClient();
        var fuser = new VertexTextFuser(
            fuserHttp, tokenProvider, options, new MdReel.Core.Domain.InMemoryCostLedger(), NullLogger<VertexTextFuser>.Instance);
        var request = new FusionRequest(
            Source: "big_buck_bunny.mp4",
            Duration: TimeSpan.FromSeconds(WindowSeconds),
            Provenance: "Generated by **mdreel** from a CC-BY recording (Blender Foundation).",
            Generator: "mdreel@0.0.0-live");

        var document = await fuser.FuseAsync(analyses, request, CancellationToken.None);

        Assert.Equal("big_buck_bunny.mp4", document.Frontmatter.Source);
        Assert.NotEmpty(document.Sections);
        Assert.All(document.Sections, s => Assert.NotEmpty(s.Blocks));
    }
}
