using System.Collections.Concurrent;
using System.Diagnostics;
using System.Globalization;
using System.Security.Cryptography;
using System.Text;
using System.Text.Json;
using System.Text.Json.Serialization;
using MdReel.Core;
using MdReel.Core.Domain;
using MdReel.Core.Output;
using MdReel.Core.Pipeline.StageA;
using MdReel.Core.Pipeline.StageB;
using MdReel.Core.Providers;
using MdReel.Infrastructure.Pipeline;
using MdReel.Infrastructure.Storage;
using Microsoft.Extensions.Options;

namespace MdReel.Api.Features.PrivateProcessing;

public sealed partial class PrivatePipelineService(
    StageARunner stageA,
    StageBRunner stageB,
    ITextFuser fuser,
    IObjectStorage objectStorage,
    ICostLedger ledger,
    IOptions<GcsOptions> gcsOptions,
    IOptions<PipelineModelOptions> modelOptions,
    IWebHostEnvironment environment,
    ILogger<PrivatePipelineService> logger)
{
    private const string GeneratorId = "mdreel@0.0.0-private";

    // Private uploads are transient: the source is deleted after processing (ARCHITECTURE.md §3,
    // Stage D). This is the body of the output's "## Source & licence" section.
    private const string PrivateProvenance =
        "Generated by **mdreel** from your uploaded recording. The source video was deleted after "
        + "processing per the default retention policy.";

    // Stage B on the private path enforces boundaries via cue hints in the prompt, not by physically
    // splitting real segments (the boundary gate verdict — PLAN.md todo 1). Physical splitting is the
    // fallback only.
    private static readonly StageBOptions PrivateStageBOptions =
        StageBOptions.Default with { ForceCueBoundarySegmentation = false };

    private static readonly JsonSerializerOptions DocumentJson = new() { WriteIndented = true };

    private readonly string _outputBucket = gcsOptions.Value.OutputBucket;
    private readonly string _rawBucket = gcsOptions.Value.RawBucket;

    // Live/Record must hand Vertex a gs:// URI it can fetch, so the raw upload is staged into
    // raw-videos-eu and deleted after Stage D (ARCHITECTURE §3/§7). Fake ignores the URI. Null in
    // config ⇒ derive from mode; an explicit value lets tests exercise the write-then-erase offline.
    private readonly bool _stageRawUploads = modelOptions.Value.StageRawUploadsToObjectStorage
        ?? modelOptions.Value.Mode != PipelineModelMode.Fake;

    private readonly ConcurrentDictionary<string, UploadState> _uploads = new(StringComparer.Ordinal);
    private readonly ConcurrentDictionary<string, JobState> _jobs = new(StringComparer.Ordinal);
    private readonly ConcurrentQueue<ErasureAuditEntry> _erasureAudit = new();
    private readonly string _uploadRoot = Path.Combine(environment.ContentRootPath, ".local-state", "uploads");

    public UploadCreatedResponse CreateUpload(HttpRequest request)
    {
        Directory.CreateDirectory(_uploadRoot);

        var uploadId = $"up_{Guid.NewGuid():N}";
        var signature = Convert.ToHexString(RandomNumberGenerator.GetBytes(16)).ToLowerInvariant();
        var targetPath = Path.Combine(_uploadRoot, $"{uploadId}.bin");

        _uploads[uploadId] = new UploadState(uploadId, signature, targetPath);

        var uploadUrl = $"{request.Scheme}://{request.Host}/api/v1/uploads/{uploadId}/content?sig={signature}";
        return new UploadCreatedResponse(uploadId, uploadUrl);
    }

    public async Task<bool> StoreUploadAsync(
        string uploadId,
        string signature,
        HttpRequest request,
        CancellationToken cancellationToken)
    {
        if (!_uploads.TryGetValue(uploadId, out var upload))
        {
            return false;
        }

        if (!string.Equals(upload.Signature, signature, StringComparison.Ordinal))
        {
            return false;
        }

        Directory.CreateDirectory(_uploadRoot);
        await using var write = File.Create(upload.Path);
        await request.Body.CopyToAsync(write, cancellationToken);
        await write.FlushAsync(cancellationToken);
        upload.Stored = true;
        return true;
    }

    public JobCreatedResponse? CreateJob(string uploadId, CreateJobOptions? options)
    {
        if (!_uploads.TryGetValue(uploadId, out var upload))
        {
            return null;
        }

        var jobId = $"job_{Guid.NewGuid():N}";
        var source = options?.Filename ?? $"{uploadId}.mp4";
        var now = DateTimeOffset.UtcNow;
        var state = new JobState
        {
            Id = jobId,
            UploadId = uploadId,
            Status = "queued",
            Stage = null,
            Progress = 0,
            Source = source,
            DurationSec = options?.DurationSec,
            CreatedAt = now,
            FinishedAt = null,
            CostCents = null,
            WallClockSec = null,
            ShouldFail = options?.Fail ?? false,
        };

        _jobs[jobId] = state;
        _ = ProcessJobAsync(state, upload);
        return new JobCreatedResponse(jobId);
    }

    public IReadOnlyList<JobListItemResponse> ListJobs() =>
        _jobs.Values
            .OrderByDescending(static x => x.CreatedAt)
            .Select(
                static x => new JobListItemResponse(
                    x.Id,
                    x.Status,
                    x.Status == "processing" ? x.Stage : null,
                    x.Progress,
                    x.Source,
                    x.DurationSec,
                    TimestampFormatter.ToUtcTimestamp(x.CreatedAt),
                    x.FinishedAt is null ? null : TimestampFormatter.ToUtcTimestamp(x.FinishedAt.Value)))
            .ToArray();

    public JobStatusResponse? GetJobStatus(string id)
    {
        if (!_jobs.TryGetValue(id, out var job))
        {
            return null;
        }

        return new JobStatusResponse(
            job.Status,
            job.Status == "processing" ? job.Stage : null,
            job.Progress,
            job.Status == "done" ? job.CostCents : null,
            job.Status == "done" ? job.DurationSec : null,
            job.Status == "done" ? job.WallClockSec : null);
    }

    public bool HasJob(string id) => _jobs.ContainsKey(id);

    public JobOutputResponse? GetOutput(string id)
    {
        if (!_jobs.TryGetValue(id, out var job))
        {
            return null;
        }

        return job.Output;
    }

    public bool DeleteJob(string id)
    {
        var removed = _jobs.TryRemove(id, out var job);
        if (!removed || job is null)
        {
            return false;
        }

        if (_uploads.TryGetValue(job.UploadId, out var upload))
        {
            TryDeleteFile(upload.Path);
        }

        // Erasure cascades to the staged raw object if the pipeline left one behind (ARCHITECTURE §7).
        _ = DeleteRawUploadAsync(job);

        _erasureAudit.Enqueue(new ErasureAuditEntry(id, DateTimeOffset.UtcNow));
        return true;
    }

    private async Task ProcessJobAsync(JobState job, UploadState upload)
    {
        var started = DateTimeOffset.UtcNow;

        // Root span per job (no parent: the HTTP request span ends at 202). jobId is the tag the
        // agent runbook searches on (TESTING.md) — one query from a red test to this trace.
        using var jobActivity = PipelineDiagnostics.Source.StartActivity(
            "pipeline.job", ActivityKind.Internal, parentContext: default);
        jobActivity?.SetTag("mdreel.job_id", job.Id);
        jobActivity?.SetTag("mdreel.upload_id", job.UploadId);
        jobActivity?.SetTag("mdreel.source", job.Source);

        try
        {
            PreparedVideo? prepared = null;
            SetProcessing(job, "A", 15);
            using (StartStage(job, "A"))
            {
                prepared = await ExecuteStageAAsync(job, upload);
            }

            if (job.ShouldFail)
            {
                SetFailed(job);
                jobActivity?.SetStatus(ActivityStatusCode.Error, "simulated failure requested");
                logger.LogWarning("Job {JobId} failed (simulated failure requested)", job.Id);
                return;
            }

            if (prepared is null)
            {
                throw new InvalidOperationException("Stage A did not produce a prepared video.");
            }

            SetProcessing(job, "B", 45);
            var sourceUri = await StageRawUploadAsync(job, upload);
            List<SegmentAnalysis> analyses;
            using (StartStage(job, "B"))
            {
                analyses = await ExecuteStageBAsync(job, sourceUri, prepared);
            }

            SetProcessing(job, "C", 75);
            OutputDocument document;
            using (StartStage(job, "C"))
            {
                document = await ExecuteStageCAsync(job, prepared, analyses);
            }

            SetProcessing(job, "D", 92);
            string markdown;
            using (StartStage(job, "D"))
            {
                markdown = await ExecuteStageDAsync(job, document);
            }

            var finishedAt = DateTimeOffset.UtcNow;
            job.Status = "done";
            job.Stage = null;
            job.Progress = 100;
            job.CostCents = SumPricedCents(job.Id);
            job.WallClockSec = Math.Max(1, (finishedAt - started).TotalSeconds);
            job.FinishedAt = finishedAt;
            job.DurationSec ??= prepared.Probe.Duration.TotalSeconds;
            job.Output = BuildOutput(job.Source, document, markdown);

            // Auto-deletion by default (ARCHITECTURE §3/§7): the local temp AND the staged raw
            // gs:// object are erased once the output exists.
            TryDeleteFile(upload.Path);
            await DeleteRawUploadAsync(job);
            jobActivity?.SetTag("mdreel.cost_cents", job.CostCents);
            LogJobDone(job.Id, job.WallClockSec.Value, job.CostCents ?? 0);
        }
        catch (Exception ex)
        {
            logger.LogError(ex, "Private pipeline failed for job {JobId}", job.Id);
            jobActivity?.SetStatus(ActivityStatusCode.Error, ex.Message);
            SetFailed(job);
            await DeleteRawUploadAsync(job);
        }
    }

    private Activity? StartStage(JobState job, string stage)
    {
        LogStageEnter(job.Id, stage);
        var activity = PipelineDiagnostics.Source.StartActivity($"pipeline.stage.{stage}");
        activity?.SetTag("mdreel.job_id", job.Id);
        activity?.SetTag("mdreel.stage", stage);
        return activity;
    }

    [LoggerMessage(Level = LogLevel.Information, Message = "Job {JobId} entering stage {Stage}")]
    private partial void LogStageEnter(string jobId, string stage);

    [LoggerMessage(Level = LogLevel.Information, Message = "Job {JobId} done in {WallClockSec}s (cost {CostCents}c)")]
    private partial void LogJobDone(string jobId, double wallClockSec, int costCents);

    private async Task<PreparedVideo> ExecuteStageAAsync(JobState job, UploadState upload)
    {
        if (!upload.Stored || !File.Exists(upload.Path))
        {
            throw new InvalidOperationException($"Upload {job.UploadId} has no stored bytes to process.");
        }

        var prepared = await stageA.PrepareAsync(job.Id, upload.Path, StageAOptions.Default, CancellationToken.None);
        job.DurationSec ??= prepared.Probe.Duration.TotalSeconds;
        return prepared;
    }

    // Vertex can only fetch a gs:// URI, so on the Live/Record path the raw upload is staged into
    // raw-videos-eu under a per-job prefix (tenant-isolated by job ownership — ARCHITECTURE §7) and
    // that gs:// URI is what Stage B sees. Fake/dev skip staging: the stand-in ignores the URI, so
    // the local path is a fine identifier and nothing needs to touch object storage.
    private async Task<string> StageRawUploadAsync(JobState job, UploadState upload)
    {
        if (!_stageRawUploads)
        {
            return upload.Path;
        }

        if (!upload.Stored || !File.Exists(upload.Path))
        {
            throw new InvalidOperationException($"Upload {job.UploadId} has no stored bytes to stage.");
        }

        var extension = Path.GetExtension(job.Source);
        if (string.IsNullOrWhiteSpace(extension))
        {
            extension = ".mp4";
        }

        var objectName = $"private/{job.Id}/source{extension}";
        await using (var read = File.OpenRead(upload.Path))
        {
            await objectStorage.WriteAsync(_rawBucket, objectName, read, CancellationToken.None);
        }

        job.RawObjectName = objectName;
        return $"gs://{_rawBucket}/{objectName}";
    }

    private async Task DeleteRawUploadAsync(JobState job)
    {
        var objectName = job.RawObjectName;
        if (string.IsNullOrEmpty(objectName))
        {
            return;
        }

        try
        {
            await objectStorage.DeleteAsync(_rawBucket, objectName, CancellationToken.None);
        }
        catch (Exception ex)
        {
            // The bucket lifecycle rule is the safety net (ARCHITECTURE §3); a failed delete must not
            // fail the job, but it must be visible.
            logger.LogWarning(ex, "Failed to delete staged raw object gs://{Bucket}/{Object} for job {JobId}",
                _rawBucket, objectName, job.Id);
        }
        finally
        {
            job.RawObjectName = null;
        }
    }

    private async Task<List<SegmentAnalysis>> ExecuteStageBAsync(JobState job, string sourceUri, PreparedVideo prepared)
    {
        List<SegmentAnalysis> analyses = [];
        foreach (var segment in prepared.Segments)
        {
            var analyzed = await stageB.AnalyzeAsync(
                sourceUri,
                segment,
                StageAOptions.Default,
                PrivateStageBOptions,
                CancellationToken.None,
                job.Id);
            analyses.AddRange(analyzed);
        }

        return [.. analyses.OrderBy(static x => x.SegmentStart).ThenBy(static x => x.SegmentIndex)];
    }

    private async Task<OutputDocument> ExecuteStageCAsync(JobState job, PreparedVideo prepared, IReadOnlyList<SegmentAnalysis> analyses)
    {
        var request = new FusionRequest(
            Source: job.Source,
            Duration: prepared.Probe.Duration,
            Provenance: PrivateProvenance,
            Generator: GeneratorId,
            JobId: job.Id);

        return await fuser.FuseAsync(analyses, request, CancellationToken.None);
    }

    private async Task<string> ExecuteStageDAsync(JobState job, OutputDocument document)
    {
        var markdown = OutputMarkdownRenderer.Render(document);
        var prefix = $"private/{job.Id}";

        await WriteUtf8Async(_outputBucket, $"{prefix}/output.md", markdown, CancellationToken.None);
        await WriteUtf8Async(
            _outputBucket,
            $"{prefix}/output.json",
            JsonSerializer.Serialize(document, DocumentJson),
            CancellationToken.None);

        return markdown;
    }

    private async Task WriteUtf8Async(string bucket, string objectName, string content, CancellationToken cancellationToken)
    {
        await using var stream = new MemoryStream(Encoding.UTF8.GetBytes(content));
        await objectStorage.WriteAsync(bucket, objectName, stream, cancellationToken);
    }

    // Every LLM call is recorded in the ledger (CLAUDE.md rule 6) — but the metering now lives where
    // the region is known: StageBRunner records each Stage B call, VertexTextFuser records the Stage C
    // call, both tagged with the EU region that served it after any 429 fallback. Fake/replay make no
    // real call and record nothing, so the E2E ledger stays exactly Stage A's two compute steps.
    private int? SumPricedCents(string jobId)
    {
        if (ledger is not InMemoryCostLedger inMemory)
        {
            return null;
        }

        var cents = inMemory.Entries
            .Where(e => string.Equals(e.JobId, jobId, StringComparison.Ordinal) && e.Cents.HasValue)
            .Sum(e => e.Cents!.Value);
        return cents;
    }

    private static JobOutputResponse BuildOutput(string sourceFilename, OutputDocument document, string markdown)
    {
        var outputFilename = $"{Path.GetFileNameWithoutExtension(sourceFilename)}.md";
        return new JobOutputResponse(outputFilename, markdown, document);
    }

    private static void SetProcessing(JobState job, string stage, double progress)
    {
        job.Status = "processing";
        job.Stage = stage;
        job.Progress = progress;
    }

    private static void SetFailed(JobState job)
    {
        job.Status = "failed";
        job.Stage = null;
        job.Progress = 100;
        job.FinishedAt = DateTimeOffset.UtcNow;
    }

    private static void TryDeleteFile(string path)
    {
        if (File.Exists(path))
        {
            File.Delete(path);
        }
    }
}

public sealed record UploadCreatedResponse(
    [property: JsonPropertyName("uploadId")] string UploadId,
    [property: JsonPropertyName("uploadUrl")] string UploadUrl);

public sealed record JobCreatedResponse(
    [property: JsonPropertyName("jobId")] string JobId);

public sealed record JobListItemResponse(
    [property: JsonPropertyName("jobId")] string JobId,
    [property: JsonPropertyName("status")] string Status,
    [property: JsonPropertyName("stage"), JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)] string? Stage,
    [property: JsonPropertyName("progress")] double Progress,
    [property: JsonPropertyName("source")] string Source,
    [property: JsonPropertyName("duration_sec"), JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)] double? DurationSec,
    [property: JsonPropertyName("created_at")] string CreatedAt,
    [property: JsonPropertyName("finished_at"), JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)] string? FinishedAt);

public sealed record JobStatusResponse(
    [property: JsonPropertyName("status")] string Status,
    [property: JsonPropertyName("stage"), JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)] string? Stage,
    [property: JsonPropertyName("progress")] double Progress,
    [property: JsonPropertyName("cost_cents"), JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)] int? CostCents,
    [property: JsonPropertyName("duration_sec"), JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)] double? DurationSec,
    [property: JsonPropertyName("wall_clock_sec"), JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)] double? WallClockSec);

public sealed record CreateJobRequest(
    [property: JsonPropertyName("uploadId")] string? UploadId,
    [property: JsonPropertyName("options")] CreateJobOptions? Options);

public sealed record CreateJobOptions(
    [property: JsonPropertyName("language_hint")] string? LanguageHint,
    [property: JsonPropertyName("retention_days")] int? RetentionDays,
    [property: JsonPropertyName("webhook_url")] string? WebhookUrl,
    [property: JsonPropertyName("quality")] string? Quality,
    [property: JsonPropertyName("fail")] bool? Fail,
    [property: JsonPropertyName("filename")] string? Filename,
    [property: JsonPropertyName("durationSec")] double? DurationSec);

public sealed record JobOutputResponse(
    string Filename,
    string Markdown,
    OutputDocument Document);

internal sealed record UploadState(string Id, string Signature, string Path)
{
    public bool Stored { get; set; }
}

internal sealed record ErasureAuditEntry(string JobId, DateTimeOffset ErasedAt);

internal sealed class JobState
{
    public required string Id { get; init; }

    public required string UploadId { get; init; }

    public required string Source { get; init; }

    public required DateTimeOffset CreatedAt { get; init; }

    public string Status { get; set; } = "queued";

    public string? Stage { get; set; }

    public double Progress { get; set; }

    public double? DurationSec { get; set; }

    public double? WallClockSec { get; set; }

    public int? CostCents { get; set; }

    public DateTimeOffset? FinishedAt { get; set; }

    public bool ShouldFail { get; set; }

    /// <summary>Object name of the staged raw upload in the raw bucket, while it exists (else null).</summary>
    public string? RawObjectName { get; set; }

    public JobOutputResponse? Output { get; set; }
}

internal static class TimestampFormatter
{
    public static string ToUtcTimestamp(DateTimeOffset value) =>
        value.UtcDateTime.ToString("yyyy-MM-ddTHH:mm:ss.fffZ", CultureInfo.InvariantCulture);
}

internal static class ProblemResponseExtensions
{
    public static async Task WriteProblemAsync(
        this HttpContext context,
        int status,
        string title,
        string detail)
    {
        context.Response.StatusCode = status;
        context.Response.ContentType = "application/problem+json";

        await context.Response.WriteAsJsonAsync(
            new
            {
                type = "about:blank",
                title,
                status,
                detail,
                instance = context.Request.Path.Value,
            });
    }
}
