using System.Globalization;
using MdReel.Core.Output;
using MdReel.Core.Providers;

namespace MdReel.Infrastructure.Pipeline;

/// <summary>
/// Deterministic stand-in for <see cref="ITextFuser"/>. Turns the (fake or replayed) Stage B
/// analyses into a valid <see cref="OutputDocument"/> — one section per segment, strictly ascending
/// timestamps, contract-clean blocks. Used in <see cref="PipelineModelMode.Fake"/>.
/// </summary>
public sealed class FakeTextFuser : ITextFuser
{
    public Task<OutputDocument> FuseAsync(
        IReadOnlyList<SegmentAnalysis> segments,
        FusionRequest request,
        CancellationToken cancellationToken)
    {
        ArgumentNullException.ThrowIfNull(segments);
        ArgumentNullException.ThrowIfNull(request);

        var sections = new List<OutputSection>(segments.Count);
        var lastSeconds = -1;
        var index = 0;
        foreach (var segment in segments)
        {
            var seconds = Math.Max((int)segment.SegmentStart.TotalSeconds, lastSeconds + 1);
            lastSeconds = seconds;

            var first = segment.Blocks.Count > 0 ? segment.Blocks[0] : null;
            var blocks = new List<OutputBlock>
            {
                new(OutputBlockLabel.Spoken, Clean(first?.Spoken) ?? $"Section {index + 1} narration."),
                new(OutputBlockLabel.Visual, Clean(first?.Visual) ?? $"Section {index + 1} visuals."),
            };

            sections.Add(new OutputSection(
                Timestamp: FormatHhmmss(seconds),
                Heading: $"Section {index + 1}",
                Blocks: blocks));
            index++;
        }

        var language = segments
            .Select(s => s.Language)
            .FirstOrDefault(l => !string.IsNullOrWhiteSpace(l)) ?? "en";

        var document = new OutputDocument(
            Frontmatter: new OutputFrontmatter(
                Title: TitleFrom(request.Source),
                Source: request.Source,
                Duration: FormatHhmmss((int)request.Duration.TotalSeconds),
                Language: language.Trim(),
                ProcessedAt: DateTimeOffset.UtcNow.ToString("yyyy-MM-ddTHH:mm:ssZ", CultureInfo.InvariantCulture),
                Generator: request.Generator,
                Summary: "Automatically generated placeholder summary of the recording.",
                Tags: ["video"]),
            Sections: sections,
            Provenance: string.IsNullOrWhiteSpace(request.Provenance) ? "Generated by mdreel." : request.Provenance.Trim());

        cancellationToken.ThrowIfCancellationRequested();
        return Task.FromResult(document);
    }

    private static string TitleFrom(string source)
    {
        var name = Path.GetFileNameWithoutExtension(source);
        return string.IsNullOrWhiteSpace(name) ? "Processed recording" : name;
    }

    private static string? Clean(string? text)
    {
        if (string.IsNullOrWhiteSpace(text))
        {
            return null;
        }

        var lines = text.Replace("\r\n", "\n", StringComparison.Ordinal)
            .Replace('\r', '\n')
            .Split('\n')
            .Select(l => l.TrimEnd())
            .Where(l => l.Length > 0 && !l.StartsWith('>') && !l.StartsWith('#') && l != "---");

        var joined = string.Join('\n', lines).Trim();
        return joined.Length == 0 ? null : joined;
    }

    private static string FormatHhmmss(int totalSeconds)
    {
        var total = Math.Max(0, totalSeconds);
        return string.Create(CultureInfo.InvariantCulture, $"{total / 3600:D2}:{total % 3600 / 60:D2}:{total % 60:D2}");
    }
}
